application: gilgistatus
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: robots\.txt

- url: /status\.css
  static_files: status.css
  upload: status\.css

- url: /update/
  script: update.app
  login: admin

- url: /appengine_admin_media
  static_dir: appengine_admin/media
  secure: never

- url: /.*
  script: gilgistatus.app

libraries:
- name: django
  version: latest