application: gilgistatus
version: 4
runtime: python
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: robots\.txt

- url: /status\.css
  static_files: status.css
  upload: status\.css

- url: /update/
  script: update.py
  login: admin

- url: /appengine_admin_media
  static_dir: appengine_admin/media
  secure: never

- url: /.*
  script: urls.py